# main menu navigation url and icon
# 配置菜单导航的名称、路径和图标icon.
menu:
  Index:
    url: /
    icon: fas fa-home
  Tags:
    url: /tags
    icon: fas fa-tags
  Categories:
    url: /categories
    icon: fas fa-bookmark
  Contact:
    url: /contact
    icon: fas fa-comments
  # 二级菜单写法如下
  #Medias:
  #  icon: fas fa-list
  #  children:
  #    - name: Musics
  #      url: /musics
  #      icon: fas fa-music
  #    - name: Movies
  #      url: /movies
  #      icon: fas fa-film
  #    - name: Books
  #      url: /books
  #      icon: fas fa-book
  #    - name: Galleries
  #      url: /galleries
  #      icon: fas fa-image

   
# Website start time.
# 站点运行开始时间.
time:
  enable: true
  year: 2019 # 年份
  month: 06 # 月份
  date: 28 # 日期
  hour: 00 # 小时
  minute: 00 # 分钟
  second: 00 # 秒


widgets:
  - tag
  - archive
  - recent_posts
  - category


# Whether to display the musics.
# 是否在首页显示音乐.
music:
  enable: true
  title: #非吸底模式有效
    enable: true
    show: 听听音乐
  autoHide: true    # hide automaticaly
  server: netease   #require  music platform: netease, tencent, kugou, xiami, baidu
  type: playlist    #require song, playlist, album, search, artist
  id: 503838841     #require  song id / playlist id / album id / search keyword
  fixed: true       # 开启吸底模式
  autoplay: true   # 是否自动播放
  theme: '#42b983'
  loop: 'all'       # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: 'random'   # 音频循环顺序, 可选值: 'list', 'random'
  preload: 'auto'   # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7       # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: true  # 列表默认折叠
  hideLrc: true     # 隐藏歌词


# social config
social:
  zhihu:
  twitter: /
  facebook: /
  linkedin:
  instagram: /
  github: beimingxinglian

user:
  name: XingLian
  avatar: /images/avatar.jpg
  location: In the dust
  description: May the Force be with you
  footnotes: #footnotes

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: true
  repo: Haojen/Claudia-theme-blog # your blog repo

# dark
# light
# user-can-set
appearance: auto # Default value is auto

# Miscellaneous
favicon: /images/favicon.png
